urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^hnofficehours/', include('hnofficehours.foo.urls')),
    (r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),
    (r'^ajax_select/', include('ajax_select.urls')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', 'views.site_index', name='index'),
    url(r'^about/$', 'views.about', name='about'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'logout/$', 'django.contrib.auth.views.logout', kwargs={'next_page': '/'}, name='logout'),
    url(r'^register/$', 'registration.views.register', name='register'),
    url(r'^register/finish/$', 'registration.views.set_password', name='set_password'), 
    url(r'^officehours/', include('officehours.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^', include('search.urls')),
    (r'^proposal/$', 'django.views.generic.simple.direct_to_template', {'template': 'originalproposal.html'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^raw_template/(?P<template>.*)', 'django.views.generic.simple.direct_to_template'),
    )

apps/officehours/forms.py
import calendar
from django.conf import settings
from django import forms
from django.utils.translation import ugettext_lazy as _
from schedule.forms import *
from schedule.models import Event
from timezones import utils as tz_utils


# If we ever go international, FIRST_DAY_OF_WEEK needs to be a user setting.
# See Calendar.firstweekday() in python ``calendar`` module for more info.
FIRST_DAY_OF_WEEK = getattr(settings, 'FIRST_DAY_OF_WEEK', 0)
# WEEKDAY_CHOICES = [(i % 7, calendar.day_name[i % 7]) for i in range(FIRST_DAY_OF_WEEK, FIRST_DAY_OF_WEEK+7)]
WEEKDAY_CHOICES = [(i % 7, calendar.day_name[i % 7]) for i in range(0, 7)]

class EventForm(SpanForm):
    repeats = forms.BooleanField(required=False)
    end_recurring_period = forms.DateTimeField(label="Repeats until",
                                               required=False,
                                               help_text = _("This date is ignored for one-time-only events."))
    repeats_on = forms.MultipleChoiceField(choices=WEEKDAY_CHOICES,
                                           required=False,
                                           widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Event
        fields = ('start', 'end', 'repeats', 'end_recurring_period',
                  'repeats_on',)

    def __init__(self, creator, hour24=False, *args, **kwargs):
        self.creator = creator
        super(EventForm, self).__init__(*args, **kwargs)
        
    def coerce_datetime_tz(self, datetime):
        server_tz = settings.TIME_ZONE
        if self.instance is None or self.instance.creator is None:
            user_tz = self.creator.get_profile().timezone
        else:
            user_tz = self.instance.creator.get_profile().timezone
        return tz_utils.adjust_datetime_to_timezone(datetime, user_tz, server_tz)
    
    def clean_start(self):
        # user was instructed to give us times in his time zone, so we
        # need to convert them to the server's.
        return self.coerce_datetime_tz(self.cleaned_data['start'])

    def clean_end(self):
        # user was instructed to give us times in his time zone, so we
        # need to convert them to the server's.
        return self.coerce_datetime_tz(self.cleaned_data['end'])


    def clean(self):
        if self.cleaned_data.get('repeats', False):
            if len(self.cleaned_data.get('repeats_on', [])) == 0:
                raise forms.ValidationError("If the events repeats, you must specific on which weekdays it repeats.")
        return self.cleaned_data

templates/schedule/_create_event_options.html
<a class="createEvent" href="{{ create_event_url }}&next={{here}}">Add Event</a>

templates/schedule/_daily_table.html
{% load scheduletags %} {% load officehourstags %} {% load timezone_filters %}
  <div class="slot_column" style="width:{{width_slot}}px;height:{{height}}px;">
    {% for slot in slots %}
    <div class="slot" style="top:{{slot.top}}px;height:{{slot.height}}px;line-height:{{slot.height}}px; width:{{width}}px;">
      {% with slot.start|localtime:output_timezone as slot_start%}
        <span class="time">{{ slot_start|time:"G:i" }}</span>
        {% if addable %}
          {% create_event_url calendar slot_start %}
        {% endif %}
      {% endwith %}
    </div>
    {% endfor %}
  </div>
  <div class="occ_column" style="left:{{width_slot}}px;width:{{width_occ}}px;height:{{height}}px;">
  {% for occ in occurrences %}
      <div href="#{% hash_occurrence occ %}" class="occ type{{occ.cls}}{% if occ.cancelled %} cancelled{% endif %}" 
      style="top:{{occ.top}}px;left:{{occ.left}}px;width:{{occ.width}}px;height:{{occ.height}}px;" onclick="openDetail(this);">
        {% options occ %}
        {% title occ %}
      </div>
      <div id="{% hash_occurrence occ %}" style="display:none;">
        {% detail occ %}
      </div>
  {% endfor %}
  </div>

templates/schedule/_detail.html
{% load i18n %}
<div class="detail">
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
    <tr>
        <td class="left">Starts</td>
        <td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
    </tr>
    <tr>
        <td class="left">Ends</td>
        <td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
    </tr>
    {% if occurrence.event.rule %}
        {% if not occurrence.id %}
            <tr>
                <td class="left">Reoccurs</td><td>{{occurrence.event.rule}}</td>
            </tr>
            {% if occurrence.event.end_recurring_period %}
                <tr>
                    <td class="left">Until</td>
                    <td>{% blocktrans with occurrence.event.end_recurring_period|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
                </tr>
            {% endif %}
        {% endif %}
    {% endif %}
</table>
{% if occurrence.description %}
<h3>Description</h3>
<p>{{occurrence.description}}</p>
{% endif %}
</div>

templates/schedule/_dialogs.html
{% block extra_head %}
{{block.super}}
<script>
function openCancelDialog(node, cancel_url, delete_url, event){
  event.stopPropagation();
  var btns = {"This":function(){window.location=cancel_url;}, "All":function(){window.location=delete_url}, "Do nothing":function(){$(this).dialog("destroy");}};
  dia = $("#delete_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openEditDialog(node, occurrence_url, event_url, event){
  event.stopPropagation();
  var btns = {"This":function(){window.location=occurrence_url;}, "All":function(){window.location=event_url}, "Do nothing":function(){$(this).dialog("destroy");}};
  dia = $("#edit_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openDetail(node){
  var btns = { "Close":function(){$(this).dialog("destroy");}};
  dia = $($(node).attr("href")).dialog({'buttons':btns, 'modal':true, 'title':'Details'});
  dia.dialog('open');
  return false;
}

function openURL(url, event){
    event.stopPropagation();
    window.location=url;
}
</script>
{% endblock %}


<div style="display:none;" id="delete_dialog" title="Question">
  Do you want to cancel this occurrence or delete all occurrences of this event?
</div>

<div style="display:none;" id="edit_dialog" title="This is a recurring event">
  Do you want to edit this occurrence or all occurrences?
</div>

templates/schedule/_event_options.html
<span class="actions">
{% if edit_event %}
<span class="edit">
{% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="#" onclick="openURL('{{ edit_occurrence }}?next={{ here }}', event);">
            <img border="0" src="{{ MEDIA_URL }}schedule/img/pencil.png" alt="Edit Event">
        </a>
    {% else %}
        <a href="#" onclick="openEditDialog(this, '{{ edit_occurrence }}?next={{ here }}', '{{ edit_event }}?next={{ here }}', event);">
            <img border="0" src="{{ MEDIA_URL }}schedule/img/pencil.png" alt="Edit Event">
        </a>
    {% endif %}
{% else %}
    <a href="#" onclick="openURL('{{ edit_event }}?next={{ here }}', event);">
        <img border="0" src="{{ MEDIA_URL }}schedule/img/pencil.png" alt="Edit Event">
    </a>
{% endif %}
{% endif %}
</span>
{% if delete_event %}
<span class="delete">
{% if occurrence.event.rule %}
    {% if occurrence.id %}
        <a href="#" onclick="openURL('{{cancel_occurrence}}?next={{here}}', event);">
            <img border="0" src="{{ MEDIA_URL }}schedule/img/delete.png" alt="Delete Event">
        </a>
    {% else %}
        <a href="#" onclick="openCancelDialog(this, '{{ cancel_occurrence }}?next={{here}}', '{{delete_event}}?next={{here}}', event);">
            <img border="0" src="{{ MEDIA_URL }}schedule/img/delete.png" alt="Delete Event">
        </a>
    {% endif %}
{% else %}
<a href="#" onclick="openURL('{{delete_event}}?next={{here}}', event);">
    <img border="0" src="{{ MEDIA_URL }}schedule/img/delete.png" alt="Delete Event">
</a>
{% endif %}
{% endif %}
</span>
</span>

templates/schedule/_month_table.html
{% load scheduletags %} {% load officehourstags %}
<table align="center" class="calendar">
{% if day_names %}
<tr class="daysofweek">
<td>&nbsp;</td>
	{% for day_name in day_names %}<td{% ifnotequal size "small" %} width='120'{% endifnotequal %}>{{ day_name }}</td>
{% endfor %}
{% endif %}
{% for week in month.get_weeks %}
    <tr>
    <td>
        <a href="{% url week_calendar %}{% querystring_for_date week.start %}">
            {{week.start|date:"W"}}
        </a>
    </td>
    {% for day in week.get_days %}
	{% day_cell calendar day month size %}
    {% endfor %}
    </tr>
{% endfor %}
</table>

templates/schedule/calendar_compact_month.html
{% extends "schedule/base.html" %}
{% load scheduletags %} {% load officehourstags %}
{% block body %}
<p align="center"><b>{{ calendar.name }}</b></p>
{% month_table calendar periods.month "small" %}
{% endblock %}

templates/schedule/calendar_list.html
{% extends "schedule/base.html" %}
{% block head_title %}Available Calendars{% endblock %}
{% block body %}
<h2>Available Calendars</h2>
<ul>
{% for cal in object_list %}
<li><b>{{ cal }}</b> : <a href="{% url compact_calendar  %}">Small Month</a> -- <a href="{% url month_calendar  %}">1 Month</a> -- <a href="{% url tri_month_calendar  %}">3 Months</a> -- <a href="{% url year_calendar  %}">This Year</a> -- <a href="{% url week_calendar  %}">Weekly</a> -- <a href="{% url day_calendar  %}">Daily</a> -- <a href="/schedule/feed/calendar/upcoming/{{ cal.id }}/">Feed</a></li><br/>
{% endfor %}
</ul>
{% endblock %}

templates/schedule/calendar_week.html
{% extends "schedule/base.html" %}
{% load scheduletags %} {% load officehourstags %}

{% block body %}

{% include "schedule/_dialogs.html" %}
<div class="tablewrapper">
    {% prevnext "week_calendar" calendar.slug periods.week "\Week W, M Y" %}
    <div class="now">
      <a href="{% url week_calendar %}">
        This week
      </a>
    </div>
    <div id="week">
      {% for day in periods.week.get_days %}
        <div class="weekday weekday{{forloop.counter}}">
          <div class="weekdayheader">
              {{day.start|date:"l, d"}}
          </div>
          <div class="weekdaytable">
          {% if forloop.first %}
              {% daily_table day 230 80 600 9 21 %}
          {% else %}
              {% daily_table day 150 15 600 9 21 %}
          {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

templates/schedule/create_event.html
{% extends "schedule/event_form_base.html" %}
{% load i18n %}

{% block schedule_nav %}{% endblock %}

{% block body %}
<form action="" method="post"> {% csrf_token %}
  <div class="pretty">
    <p class="help">{% trans "Create or change event. Enter all times local to your timezone." %}</p>
    <p>{{ form.start.label_tag }}{{ form.start }}</p>
    <p>{{ form.end.label_tag }}{{ form.end }}</p>
    <p class="help">{{ form.end.help_text}}</p>
    <p>{{ form.repeats.label_tag }} {{ form.repeats }}</p>
    <p>{{ form.end_recurring_period.label_tag }}{{ form.end_recurring_period }}</p>
    <p class="help">{{ form.end_recurring_period.help_text}}</p>
    <p style="float:left;">{{ form.repeats_on.label_tag }}</p>
    {{ form.repeats_on }}
    <div class="footer">
      <input type="submit" value="{% trans 'Save' %}">
      <input type="hidden" name="next" value="{{next|default:""}}">
    </div>
  </div>
</form>
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    {# TODO WHERE DOES THIS BLOCK GO? event_form_base.html ? base.html ? #}
<style>
/* hacky css */
  .disable { opacity: 0.3; }
</style>
<script type="text/javascript">
function doStuff(){
  $('form div.pretty > *:gt(3):not(:last)').toggleClass('disable',function() { return !$('#id_repeats').is(':checked'); });
}
$(function(){
  $('#id_repeats').click(doStuff);
  doStuff();
});
</script>
{% endblock extra_head %}

templates/schedule/edit_occurrence.html
{% extends "schedule/event_form_base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change occurrence. All fields are required." %}</b>
<br/><br/>
<form action="" method="post"> {% csrf_token %}
<table>
{{ form.as_table }}
</table>
<br/>
<input type="submit" value="{% trans "Save" %}">
<input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
<input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

templates/schedule/event.html
{% extends "schedule/base.html" %}
{% load i18n %}
{% load scheduletags %} {% load officehourstags %}
{% load timezone_filters %}
{% block body %}
{# <div class="navigation pretty"> #}
{#   <h2>View</h2> #}
{#   <ul> #}
{#   <li><a href="{% url day_calendar %}{% querystring_for_date event.start 3 %}"> #}
{#     Day #}
{#   </a></li> #}
{#   <li><a href="{% url month_calendar %}{% querystring_for_date event.start 2 %}"> #}
{#     Month #}
{#   </a></li> #}
{#   <li><a href="{% url year_calendar %}{% querystring_for_date event.start 1%}"> #}
{#     Year #}
{#   </a></li> #}
{#   {% if back_url %} #}
{#   <li><a href="{{ back_url }}"> #}
{#     <img border="0" src="{{ MEDIA_URL }}left_mod.png" alt="{% trans "Back" %}"/> #}
{#   </a></li> #}
{#   {% endif %} #}
{#   </ul> #}
{# </div> #}
<h2 align="center">{{event.title}}</h2>
<table align="center" class="pretty">
  <thead>
    <tr><td colspan="2">Office Hours</td></tr>
  </thead>
  <tbody>
    <tr>
      <td>Starts</td>
      <td>{% blocktrans with event.start|localtime:output_timezone|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
      </tr>
      <tr>
      <td>Ends</td>
      <td>{% blocktrans with event.end|localtime:output_timezone|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
    </tr>
    <tr>
    <td>Reoccurs</td>
    {% if event.rule %}
    <td>{{ event.rule }} until {% blocktrans with event.end_recurring_period|date:_("DATETIME_FORMAT") as end_recurring_date %}{{ end_recurring_date }}{% endblocktrans %}</td>
    {% else %}
    <td>{% trans "Never. This is a 'one time only' event." %}</td>
    {% endif %}
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <td>Actions</td>
      <td>
        <a href="{% url edit_event event_id=event.id %}">
          <img border="0" src="{{ MEDIA_URL }}pencil.png" alt="{% trans "Edit" %}"/>
        </a>
        &nbsp;
        <a href="{% url delete_event event.id %}">
          <img border="0" src="{{ MEDIA_URL }}delete.png" alt="{% trans "Delete" %}"/>
        </a>
      </td>
    </tr>
  </tfoot>
</table>
{% if event.description %}
<h3>Description</h3>
<p>{{event.description}}</p>
{% endif %}

{% endblock %}

templates/schedule/event_form_base.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}schedule/js/jquery.timePicker.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_start_0").datepicker({
          dateFormat: $.datepicker.ATOM,
          onSelect: function(dateText,inst){ $("#id_end_0").val(dateText); }  // automagically set end to the same date
        });
        $("#id_end_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_start_1").timePicker();
        $("#id_end_1").timePicker();
        $("#id_end_recurring_period").datepicker({dateFormat: $.datepicker.ATOM});
        var oldTime = $.timePicker("#id_start_1").getTime();
        $("#id_start_1").change(function() {
          if ($("#id_end_1").val()) { // Only update when second input has a value.
            // this block probably comes from http://labs.perifer.se/timedatepicker/
            // Calculate duration.
            var duration = ($.timePicker("#id_end_1").getTime() - oldTime);
            var time = $.timePicker("#id_start_1").getTime();
            // Calculate and update the time in the second input.
            $.timePicker("#id_end_1").setTime(new Date(time.getTime() + duration));
            oldTime = time;
          } else {  // automagically populate an hour TODO magic number
            var time = $.timePicker("#id_start_1").getTime();
            $.timePicker("#id_end_1").setTime(new Date(time.getTime() + 60*60*1000));
          }
          if (!$("#id_start_0").val() && !$("#id_end_0").val()) { //  automagically populate with today
            $("#id_start_0,#id_end_0").datepicker("setDate","today");
          }
        });
        // Validate.
        // TODO this should validate date AND time
        $("#id_end_1").change(function() {
          if($.timePicker("#id_start_1").getTime() > $.timePicker(this).getTime()) {
          $(this).addClass("error");
          }
          else {
          $(this).removeClass("error");
          }
        });
    });
    </script>
{% endblock %}

templates/schedule/occurrence.html
{% extends "schedule/base.html" %}
{% load i18n %}
{% load scheduletags %} {% load officehourstags %}

{% block body %}
<div class="navigation">
  <a href="{% url day_calendar  %}{% querystring_for_date occurrence.start 3 %}">
    Day
  </a>
  <a href="{% url month_calendar  %}{% querystring_for_date occurrence.start 2 %}">
    Month
  </a>
</div>
<div class="event_actions" align="center">
	{% if back_url %}
	<a href="{{ back_url }}"><img border="0" src="{{ MEDIA_URL }}left_mod.png" alt="{% trans "Back" %}"></a> &nbsp;
	{% endif %}
	<a href="{{occurrence.get_edit_url}}"><img border="0" src="{{ MEDIA_URL }}pencil.png" alt="{% trans "Change" %}"></a> &nbsp;
	<a href="{{occurrence.get_cancel_url}}"><img border="0" src="{{ MEDIA_URL }}delete.png" alt="{% trans "Cancel" %}"></a>
</div>
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
<tr>
<td>Starts</td>
<td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Ends</td>
<td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
</tr>
{% if occurrence.event.rule %}
<tr>
<td>Reoccurs</td><td>{{event.rule}}</td>
</tr>
{% endif %}
</table>
{% if occurrence.description %}
<h3>Description</h3>
<p>{{occurrence.description}}</p>
{% endif %}

{% endblock %}